
Muestra las primeras 5 filas del conjunto de datos.

Muestra las últimas 5 filas del conjunto de datos.

Muestra una muestra aleatoria de 5 filas del conjunto de datos.

In [34]:
import pandas as pd
import numpy as np

In [4]:
df_world_data = pd.read_csv("files\world-data-2023_part1.csv", index_col=0)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\aliri\AppData\Local\Temp\ipykernel_2212\2437521921.py:1: SyntaxWarning: invalid escape sequence '\w'
  df_world_data = pd.read_csv("files\world-data-2023_part1.csv", index_col=0)

In [5]:
df_world_data.head()

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [6]:
df_world_data.tail()

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

In [8]:
df_world_data.sample(5)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
89,Kiribati,147,KI,42.00%,811,NaN,27.89,686.0,South Tarawa,66,99.55,0.60%,AUD,3.57,15.00%,NaN
45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858","134,000",41.18,243.0,Kinshasa,"2,021",133.85,2.90%,CDF,5.92,67.20%,$1.49
178,Tunisia,76,TN,64.80%,"163,610","48,000",17.56,216.0,Tunis,"29,937",155.33,6.70%,TND,2.20,6.80%,$0.73
40,Costa Rica,100,CR,34.50%,"51,100","10,000",13.97,506.0,San Jos������,"8,023",128.85,2.10%,CRC,1.75,54.60%,$0.98
142,Romania,84,RO,58.80%,"238,391","126,000",9.60,40.0,Bucharest,"69,259",123.78,3.80%,RON,1.71,30.10%,$1.16

Muestra el nombre de todas las columnas en el conjunto de datos.

Muestra los valores únicos en la columna "Abbreviation".

Cuenta cuántas veces aparece cada valor único en la columna "Abbreviation".

In [11]:
df_world_data.columns

Index(['Country', 'Density\r\n(P/Km2)', 'Abbreviation',
       'Agricultural Land( %)', 'Land Area(Km2)', 'Armed Forces size',
       'Birth Rate', 'Calling Code', 'Capital/Major City', 'Co2-Emissions',
       'CPI', 'CPI Change (%)', 'Currency-Code', 'Fertility Rate',
       'Forested Area (%)', 'Gasoline Price'],
      dtype='str')

In [12]:
df_world_data["Abbreviation"].unique()

<StringArray>
['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT',
 ...
 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE', 'ZM', 'ZW']
Length: 189, dtype: str

In [13]:
df_world_data["Abbreviation"].value_counts()

Abbreviation
AF    1
AL    1
DZ    1
AD    1
AO    1
     ..
VE    1
VN    1
YE    1
ZM    1
ZW    1
Name: count, Length: 188, dtype: int64

Verifica si hay valores nulos en el conjunto de datos.

Verifica si hay valores no nulos en el conjunto de datos.

Muestra información general sobre el conjunto de datos.

In [16]:
df_world_data.isna()

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
194,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [17]:
df_world_data.isna().sum()

Country                   0
Density\r\n(P/Km2)        0
Abbreviation              7
Agricultural Land( %)     7
Land Area(Km2)            1
Armed Forces size        24
Birth Rate                6
Calling Code              1
Capital/Major City        3
Co2-Emissions             7
CPI                      17
CPI Change (%)           16
Currency-Code            15
Fertility Rate            7
Forested Area (%)         7
Gasoline Price           20
dtype: int64

In [15]:
df_world_data.isna().sum()/df_world_data.shape[0]*100,2

(Country                   0.000000
 Density\r\n(P/Km2)        0.000000
 Abbreviation              3.589744
 Agricultural Land( %)     3.589744
 Land Area(Km2)            0.512821
 Armed Forces size        12.307692
 Birth Rate                3.076923
 Calling Code              0.512821
 Capital/Major City        1.538462
 Co2-Emissions             3.589744
 CPI                       8.717949
 CPI Change (%)            8.205128
 Currency-Code             7.692308
 Fertility Rate            3.589744
 Forested Area (%)         3.589744
 Gasoline Price           10.256410
 dtype: float64,
 2)

In [22]:
df_world_data.notnull()

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,False,True,True,True,True,False,False,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
191,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
192,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
193,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
194,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

In [23]:
df_world_data.notnull().sum()

Country                  195
Density\r\n(P/Km2)       195
Abbreviation             188
Agricultural Land( %)    188
Land Area(Km2)           194
Armed Forces size        171
Birth Rate               189
Calling Code             194
Capital/Major City       192
Co2-Emissions            188
CPI                      178
CPI Change (%)           179
Currency-Code            180
Fertility Rate           188
Forested Area (%)        188
Gasoline Price           175
dtype: int64

In [19]:
df_world_data.describe()

       Birth Rate  Calling Code  Fertility Rate
count  189.000000    194.000000      188.000000
mean    20.214974    360.546392        2.698138
std      9.945774    323.236419        1.282267
min      5.900000      1.000000        0.980000
25%     11.300000     82.500000        1.705000
50%     17.950000    255.500000        2.245000
75%     28.750000    506.750000        3.597500
max     46.080000   1876.000000        6.910000

In [21]:
df_world_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    str
 1   Density
(P/Km2)       195 non-null    str
 2   Abbreviation           188 non-null    str
 3   Agricultural Land( %)  188 non-null    str
 4   Land Area(Km2)         194 non-null    str
 5   Armed Forces size      171 non-null    str
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    str
 9   Co2-Emissions          188 non-null    str
 10  CPI                    178 non-null    str
 11  CPI Change (%)         179 non-null    str
 12  Currency-Code          180 non-null    str
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    str
 15  Gasoline Price         175 non-null    str
dtypes: float64(3), str(13)
memory usage: 24.5 KB

In [24]:
df_world_data.shape

(195, 16)

In [25]:
df_world_data.value_counts()

Country              Density\r\n(P/Km2)  Abbreviation  Agricultural Land( %)  Land Area(Km2)  Armed Forces size  Birth Rate  Calling Code  Capital/Major City      Co2-Emissions  CPI       CPI Change (%)  Currency-Code  Fertility Rate  Forested Area (%)  Gasoline Price
Afghanistan          60                  AF            58.10%                 652,230         323,000            32.49       93.0          Kabul                   8,672          149.9     2.30%           AFN            4.47            2.10%              $0.70             1
Albania              105                 AL            43.10%                 28,748          9,000              11.78       355.0         Tirana                  4,536          119.05    1.40%           ALL            1.62            28.10%             $1.36             1
Algeria              18                  DZ            17.40%                 2,381,741       317,000            24.28       213.0         Algiers                 150,006        151.36    2.00%           DZD            3.02            0.80%              $0.28             1
Angola               26                  AO            47.50%                 1,246,700       117,000            40.73       244.0         Luanda                  34,693         261.73    17.10%          AOA            5.52            46.30%             $0.97             1
Antigua and Barbuda  223                 AG            20.50%                 443             0                  15.33       1.0           St. John's, Saint John  557            113.81    1.20%           XCD            1.99            22.30%             $0.99             1
                                                                                                                                                                                                                                                                               ..
Uruguay              20                  UY            82.60%                 176,215         22,000             13.86       598.0         Montevideo              6,766          202.92    7.90%           UYU            1.97            10.70%             $1.50             1
Venezuela            32                  VE            24.50%                 912,050         343,000            17.88       58.0          Caracas                 164,175        2,740.27  254.90%         VED            2.27            52.70%             $0.00             1
Vietnam              314                 VN            39.30%                 331,210         522,000            16.75       84.0          Hanoi                   192,668        163.52    2.80%           VND            2.05            48.10%             $0.80             1
Yemen                56                  YE            44.60%                 527,968         40,000             30.45       967.0         Sanaa                   10,609         157.58    8.10%           YER            3.79            1.00%              $0.92             1
Zambia               25                  ZM            32.10%                 752,618         16,000             36.19       260.0         Lusaka                  5,141          212.31    9.20%           ZMW            4.63            65.20%             $1.40             1
Name: count, Length: 142, dtype: int64

In [ ]:
df_world_data.isna().sum().any()
#con esta operacion podemos ver si existe algun nulo en el dataframe, como un booleano

np.True_

In [ ]:
df_world_data.notnull().sum().any()
#con esta operacion podemos ver si existe algun No nulo en el dataframe, como un booleano

np.True_

Elimina una columna específica (por ejemplo, "Armed Forces size").

In [32]:
df_sin_columna = df_world_data.drop(columns = ["Armed Forces size"])

In [33]:
df_sin_columna.head()

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

Selecciona las columnas numéricas del conjunto de datos y muestra sus estadísticas descriptivas básicas (para esto tendréis que usar el método '.describe(), su documentación la tenéis

In [36]:
df_world_data.describe(exclude=["object"]).T

,count,mean,std,min,25%,50%,75%,max
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91

In [37]:
df_world_data.describe(exclude="object").T

,count,mean,std,min,25%,50%,75%,max
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91

In [40]:
df_world_data.describe(include="object")

C:\Users\aliri\AppData\Local\Temp\ipykernel_2212\1884576185.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_world_data.describe(include="object")

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Forested Area (%),Gasoline Price
count,195,195,188,188,194,171,192,188,178,179,180,188,175
unique,195,137,188,168,194,105,192,184,175,86,133,161,101
top,Afghanistan,25,AF,17.40%,"652,230","2,000",Kabul,495,106.58,1.80%,EUR,32.70%,$0.71
freq,1,7,1,3,1,7,1,2,2,7,23,3,6

In [41]:
df_world_data.describe(include="all")

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
count,195,195,188,188,194,171,189.000000,194.000000,192,188,178,179,180,188.000000,188,175
unique,195,137,188,168,194,105,NaN,NaN,192,184,175,86,133,NaN,161,101
top,Afghanistan,25,AF,17.40%,"652,230","2,000",NaN,NaN,Kabul,495,106.58,1.80%,EUR,NaN,32.70%,$0.71
freq,1,7,1,3,1,7,NaN,NaN,1,2,2,7,23,NaN,3,6
mean,NaN,NaN,NaN,NaN,NaN,NaN,20.214974,360.546392,NaN,NaN,NaN,NaN,NaN,2.698138,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.945774,323.236419,NaN,NaN,NaN,NaN,NaN,1.282267,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,5.900000,1.000000,NaN,NaN,NaN,NaN,NaN,0.980000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,11.300000,82.500000,NaN,NaN,NaN,NaN,NaN,1.705000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,17.950000,255.500000,NaN,NaN,NaN,NaN,NaN,2.245000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,28.750000,506.750000,NaN,NaN,NaN,NaN,NaN,3.597500,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,46.080000,1876.000000,NaN,NaN,NaN,NaN,NaN,6.910000,NaN,NaN