
1.¿Qué diferencia hay entre una Serie y un DataFrame?
-La serie es unidimensional, el dataframe es bidimensional.
-La serie admite solo un tipo de dato y el dataframe distintos
-La indexación en dataframe tenemos loc y el iloc

In [29]:
import numpy as np
import pandas as pd

In [6]:
#2.Es el turno de los DataFrames:
##Crea un array de dos dimensiones con 4 filas y 3 columnas.

array_paises= np.empty((4, 3))
print(array_paises)

[[7.63125925e-312 7.63125925e-312 7.63125925e-312]
 [1.26974871e-321 9.81339012e-153 1.35077468e+161]
 [2.12896695e-052 3.92575259e-033 2.81898630e+179]
 [5.28899091e+174 3.63070688e+179 8.69523574e-071]]

In [14]:
#Primero lo hemos convertido en un DataFrame
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia"
df_paises=pd.DataFrame(array_paises)
df_paises

               0              1              2
0  7.631259e-312  7.631259e-312  7.631259e-312
1  1.269749e-321  9.813390e-153  1.350775e+161
2   2.128967e-52   3.925753e-33  2.818986e+179
3  5.288991e+174  3.630707e+179   8.695236e-71

In [19]:
df_paises.columns = ["España","Francia","Italia"]
df_paises

          España        Francia         Italia
0  7.631259e-312  7.631259e-312  7.631259e-312
1  1.269749e-321  9.813390e-153  1.350775e+161
2   2.128967e-52   3.925753e-33  2.818986e+179
3  5.288991e+174  3.630707e+179   8.695236e-71

In [6]:
#Descarga el archivo "medallas" y carga el DataFrame.
#index_col=0  ------> Usa la primera columna del CSV como índice
#pandas siempre tiene índice ✔️
#Tú decides si usar uno automático o uno personalizado ✔️
#index_col es solo para personalizarlo

medallas=pd.read_csv("files/medallas.csv",index_col=0)

In [7]:
medallas.sample(5)

               País  Oro  Plata  Bronce
3     Corea del Sur  745    663     827
10  Corea del Norte   91    120     235
4              Irán  179    181     197
7         Tailandia  132    175     278
8         Indonesia  112    131     240

In [8]:
medallas.columns

Index(['País', 'Oro', 'Plata', 'Bronce'], dtype='str')

Usando el loc:Usando el loc extrae todas las columnas de la fila de Tailandia.
---- > Lo que te pide el ejercicio:Extrae todas las columnas de la fila de Tailandia.Eso significa: Fila → "Tailandia" -- Columnas → todas
Aquí el índice es Unnamed: 0, NO “País”.

Entonces, ¿puedes usar .loc["Tailandia"]?

# NO directamente ❌Porque .loc busca en el índice, y ahí hay números (1, 2, 3…), no países

Cómo hacerlo con MI código?(Más adelante, en otras lecciones pondremos el indice paises, (LO HAGO MÁS ABAJO PAA QUE SEA MÁS FACIL BUSCAR CON EL LOC)
👉 Crea una condición (True/False)
medallas["País"] == "Tailandia"

1. ¿Qué es medallas["País"]?En pandas eso selecciona una columna.No devuelve datos, devuelve un “mapa” de qué filas cumplen la condición
👉 Resultado: una lista de valores (Serie), algo así:

China
Indonesia
Japón
Corea del Norte
China Taipéi
Tailandia

¿Qué hace == "Tailandia"?
Aquí estás comparando cada valor de esa columna con "Tailandia".
pandas lo hace elemento por elemento (no solo una vez).

Resultado de la condición:

False
False
False
False
False
True

Solo es True donde el país es "Tailandia".

👉 Selecciona las filas donde es True
.loc[...]

Tailandia =medallas.loc[medallas["País"] == "Tailandia"]

In [47]:
#Usando el loc:Usando el loc extrae todas las columnas de la fila de Tailandia.
# ---- > Lo que te pide el ejercicio:Extrae todas las columnas de la fila de Tailandia.Eso significa: Fila → "Tailandia" -- Columnas → todas

medallas=pd.read_csv("files/medallas.csv",index_col="País")
medallas.head (4)

               Unnamed: 0   Oro  Plata  Bronce
País
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827
Irán                    4   179    181     197

In [49]:
#Recordemos cómo cargaste tu CSV:medallas = pd.read_csv("files/medallas.csv", index_col="País").
# Ahora PAIS es el INDICE y las Columnas: "Oro", "Plata", "Bronce"

#dataframe.loc[fila, columna]

#Si quieres todas las columnas de una fila, puedes dejar la parte de columna vacía o usar :

Tailandia=medallas.loc["Tailandia", :] # ---> OPCIÓN 1

# ----> "Tailandia" → fila que quieres
# ----> : → todas las columnas

#Como por defecto .loc devuelve todas las columnas si no pones nada:

#medallas = medallas.loc["Tailandia"] #---> OPCIÓN 2
#Hace exactamente lo mismo.Devuelve una Serie en lugar de un DataFrame, pero puedes acceder a los valores igual

Tailandia

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

In [ ]:
#OJO !!!CUANDO aparece la primera columna Unnamed: 0, significa que tu CSV ya tenía un índice guardado,
# (probablemente al guardarlo con to_csv() antes) y pandas lo leyó como columna normal.
#Qué hacer????
# -------> Borrar la columna Unnamed: 0 (la más simple)
medallas = medallas.drop(columns=["Unnamed: 0"])
medallas.head()

#SI DA ERROR ES XQ YA SE HABÍA BORRADO LA COLUMNA UNNAMED y he vuelto a ejecutar la celda sin querer

KeyError: "['Unnamed: 0'] not found in axis"

In [51]:
#Usando el loc extrae todas las columnas de China e Irán.

#RECORDAMOS  dataframe.loc[fila(S), columna(s)]

china_iran = medallas.loc[['China', 'Irán'], :]
china_iran

        Oro  Plata  Bronce
País
China  1473    994     720
Irán    179    181     197

In [56]:
#Usando el loc extrae solo las columnas de "Oro", "Plata" de China e Irán.

##RECORDAMOS  dataframe.loc[[fila(S)], [columna(s)]]

OroPlata=medallas.loc[["China","Irán"],["Oro","Plata"]]
OroPlata

        Oro  Plata
País
China  1473    994
Irán    179    181

In [60]:
medallas

                  Oro  Plata  Bronce
País
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [62]:
#Usando el iloc extrae la información de la India. Devolved todas las columnas.

India=medallas.iloc[5, :]
India

Oro       154
Plata     202
Bronce    315
Name: India, dtype: int64

In [ ]:
#Alternativa si quieres mantener DataFrame.Devuelve un DataFrame con 1 fila
India = medallas.iloc[[5], :]  # dobles corchetes
India

#Aquí he podido contar en el dataframe y ver en que posición está India, sin embargo en un csv grande es mejor usar loc y buscar por país si es el indice

       Oro  Plata  Bronce
País
India  154    202     315

In [ ]:
#Usando el iloc extrae todas las columnas de los países que estén en posición impar. 
#La primera que nos tendría que salir es Japón y la última Corea del Norte.

###RECORDAMOS  dataframe.loc[[fila(S)], [columna(s)]]

paises_posicion_impar=medallas.iloc[1::2, :]

#1::2 → selecciona filas impares

#: → selecciona todas las columnas

#Resultado → un DataFrame con todas las columnas, pero solo de las filas en posiciones impares

paises_posicion_impar

                  Oro  Plata  Bronce
País
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

In [77]:
#Utilizando el código del ejercicio anterior, selecciona unicamente las columnas , "Plata" y "Bronce".
paises_posicion_impar_plata_bronce=medallas.iloc[1::2, [1,2]]

#¿porque una cosa va sin corchetes y la otra con corchetes?

####tiene que ver con la diferencia entre slices y listas en Python/pandas

#1.Antes de la coma: filas (1::2) ----->

#1::2 → es un slice, no una lista
#Los slices en Python se escriben sin corchetes, con formato start:stop:step
#Selecciona filas en posiciones impares: 1, 3, 5 …

#✅ No necesitamos corchetes extra porque ya es un slice válido.

#2.Después de la coma: columnas ([1, 2]) ---->
#[1, 2] → lista de posiciones

#Necesitamos corchetes porque queremos seleccionar columnas específicas

#Aquí no usamos slice (start:stop:step), sino elementos exactos: columna 1 y columna 2



paises_posicion_impar_plata_bronce

                 Plata  Bronce
País
Japón             1037     985
Irán               181     197
India              202     315
Indonesia          131     240
Corea del Norte    120     235

In [85]:
#Contesta a las siguientes preguntas:

#¿Qué país consiguió más de 200 medallas de oro? 
condicion=medallas["Oro"]>200 #---> medallas["Oro"] --->selecciona la columna de Oro,> 200 → devuelve un Boolean Series con True para los que cumplen la condición
paises_mas_200_oro = medallas[condicion]
print(paises_mas_200_oro)


###ALTERNATIVA EN UNA SOLA LINEA

###El primer medallas (antes de los corchetes):Este es el DataFrame completo
###El segundo medallas (dentro de los corchetes):Aquí estamos accediendo a la columna "Oro" del DataFrame medallas
####### medallas["Oro"] → devuelve una Serie con los valores de oro

paises_mas_200_oro = medallas[medallas["Oro"] > 200]
paises_mas_200_oro

                Oro  Plata  Bronce
País
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827

                Oro  Plata  Bronce
País
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827

In [88]:
#¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

Condicion2=(medallas["Oro"]>200) & (medallas["Plata"]>1000)

oro200_plata1000=medallas[Condicion2]

oro200_plata1000

        Oro  Plata  Bronce
País
Japón  1032   1037     985

In [90]:
#¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

condicion3=(medallas["Oro"]>200) | (medallas["Bronce"]>700)
oro200_bronce700=medallas[condicion3]

oro200_bronce700

                Oro  Plata  Bronce
País
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827

In [ ]:
#Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

##Antes de sumar, conviene confirmar qué columnas tenemos:
medallas.columns

Index(['Oro', 'Plata', 'Bronce'], dtype='str')

Paso 2: Sumar las columnas fila por fila

-En pandas, podemos usar la función .sum() con el parámetro axis=1:
- axis=0 → suma columnas verticalmente (por cada columna)

- axis=1 → suma horizontalmente, fila por fila

In [99]:
Total_medallas= medallas[["Oro", "Plata", "Bronce"]].sum(axis=1)
medallas.insert(3, "Total", Total_medallas)

#4 → posición de la columna (en este ejemplo, después de Oro, Plata y Bronce)

# "Total" → nombre de la columna

#Total_medallas → la Serie con la suma de medallas por país

ValueError: cannot insert Total, already exists

In [ ]:
##OOOOOOJOOOOOO !!!!ME DA EL ERROR XQ LA COLUMAN YA EXISTE, LO HE EJECUTADO DOS VECES SIN DARME CUENTA

In [ ]:
medallas 
#Vemos que efectivamente hemos creado la columna total

                  Oro  Plata  Bronce  Total
País
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446

Diferencia entre insert y asignación directa

medallas["Total"] = ... → añade la columna al final del DataFrame

medallas.insert(pos, "Total", ...) → añade la columna en la posición que quieras

💡 Tip:

Siempre que uses insert, la posición debe estar entre 0 y el número actual de columnas.

Si intentas insertar en una posición fuera de rango, pandas lanzará un error.

In [ ]:
##Para probar, voy a insertar una nuevo columna (que no piden los ejercicios ) por ASIGNACIÓN DIRECTA

#Me invento una condición
Total_medallas_oro_plata= medallas[["Oro", "Plata"]].sum(axis=1) # ----> condicion

medallas["total_oro_plata"]=Total_medallas_oro_plata # ----->
## -Crea una nueva columna llamada "total_oro_plata" en el DataFrame medallas.

## - Asigna los valores de la Serie Total_medallas_oro_plata a esa columna

medallas

                  Oro  Plata  Bronce  Total  total_oro_plata
País
China            1473    994     720   3187             2467
Japón            1032   1037     985   3054             2069
Corea del Sur     745    663     827   2235             1408
Irán              179    181     197    557              360
Kazajistán        155    158     224    537              313
India             154    202     315    671              356
Tailandia         132    175     278    585              307
Indonesia         112    131     240    483              243
China Taipéi       99    144     276    519              243
Corea del Norte    91    120     235    446              211