In [1]:
import pandas as pd
import numpy as np

In [5]:
df_world_1=pd.read_csv("files\world-data-2023_part1.csv")
df_world_1.head(3)

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\DAVID\AppData\Local\Temp\ipykernel_25920\2607850521.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df_world_1=pd.read_csv("files\world-data-2023_part1.csv")

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28

In [4]:
df_world_2=pd.read_csv("files\world-data-2023_part2.csv")
df_world_2.head(3)

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\DAVID\AppData\Local\Temp\ipykernel_25920\406115980.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df_world_2=pd.read_csv("files\world-data-2023_part2.csv")

,Unnamed: 0,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,1,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,2,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"

In [9]:
pd.Series(df_world_1.columns)

<bound method Series.sum of 0                Unnamed: 0
1                   Country
2          Density\n(P/Km2)
3              Abbreviation
4     Agricultural Land( %)
5            Land Area(Km2)
6         Armed Forces size
7                Birth Rate
8              Calling Code
9        Capital/Major City
10            Co2-Emissions
11                      CPI
12           CPI Change (%)
13            Currency-Code
14           Fertility Rate
15        Forested Area (%)
16           Gasoline Price
dtype: str>

In [8]:
pd.Series(df_world_2.columns)

0                                    Unnamed: 0
1                                           GDP
2        Gross primary education enrollment (%)
3       Gross tertiary education enrollment (%)
4                              Infant mortality
5                                  Largest city
6                               Life expectancy
7                      Maternal mortality ratio
8                                  Minimum wage
9                             Official language
10             Out of pocket health expenditure
11                      Physicians per thousand
12                                   Population
13    Population: Labor force participation (%)
14                              Tax revenue (%)
15                               Total tax rate
16                            Unemployment rate
17                             Urban_population
18                                      country
19                                  coordinates
dtype: str

In [13]:
df_world_1.shape

(195, 17)

In [14]:
df_world_2.shape

(195, 20)

In [16]:
df_world_1["Country"]

0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...
190      Venezuela
191        Vietnam
192          Yemen
193         Zambia
194       Zimbabwe
Name: Country, Length: 195, dtype: str

In [17]:
df_world_2["country"]

0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...
190      Venezuela
191        Vietnam
192          Yemen
193         Zambia
194       Zimbabwe
Name: country, Length: 195, dtype: str

In [24]:
#debes seleccionar el método de unión de Pandas que consideres más apropiado para esta situación y justificar por qué crees que ese método es el mejor en tu informe.

#Vamos a explorar los métodos merge y join porque parece que los dos métodos son apropiados

df_world_merge = df_world_1.merge(df_world_2,left_on="Country",right_on="country")
df_world_merge.head()

,Unnamed: 0_x,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

In [25]:
df_world_merge.drop(columns=["country"], inplace=True)

In [26]:
df_world_merge.head()

,Unnamed: 0_x,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,...,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,...,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,...,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,...,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

In [27]:
df_world_merge.drop(columns=["Unnamed: 0_x"], inplace=True)

In [29]:
df_world_merge.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"

In [33]:

#2.Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

#No tengan espacios.

df_world_merge.columns = [col.replace(" ", "") for col in df_world_merge]

In [ ]:
df_world_merge[columns].str.lower()

In [34]:
df_world_merge.columns = [ 
    col.strip() # Quita espacios sobrantes al inicio y final
    .lower() # Todo a minúsculas .replace("\n", "")  Elimina saltos de línea 
    .replace(":", "") # Elimina los dos puntos 
    .replace(" ", "_") # Cambia espacios internos por guiones bajos
      for col in df_world_merge.columns
 ]

In [35]:
df_world_merge.head()

,country,density\n(p/km2),abbreviation,agriculturalland(%),landarea(km2),armedforcessize,birthrate,callingcode,capital/majorcity,co2-emissions,...,officiallanguage,outofpockethealthexpenditure,physiciansperthousand,population,populationlaborforceparticipation(%),taxrevenue(%),totaltaxrate,unemploymentrate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"