
1.¿Qué diferencia hay entre una Serie y un DataFrame?
-La serie es unidimensional, el dataframe es bidimensional.
-La serie admite solo un tipo de dato y el dataframe distintos
-La indexación en dataframe tenemos loc y el iloc

In [3]:
import numpy as np
import pandas as pd

In [6]:
#2.Es el turno de los DataFrames:
##Crea un array de dos dimensiones con 4 filas y 3 columnas.

array_paises= np.empty((4, 3))
print(array_paises)

[[7.63125925e-312 7.63125925e-312 7.63125925e-312]
 [1.26974871e-321 9.81339012e-153 1.35077468e+161]
 [2.12896695e-052 3.92575259e-033 2.81898630e+179]
 [5.28899091e+174 3.63070688e+179 8.69523574e-071]]

In [14]:
#Primero lo hemos convertido en un DataFrame
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia"
df_paises=pd.DataFrame(array_paises)
df_paises

               0              1              2
0  7.631259e-312  7.631259e-312  7.631259e-312
1  1.269749e-321  9.813390e-153  1.350775e+161
2   2.128967e-52   3.925753e-33  2.818986e+179
3  5.288991e+174  3.630707e+179   8.695236e-71

In [19]:
df_paises.columns = ["España","Francia","Italia"]
df_paises

          España        Francia         Italia
0  7.631259e-312  7.631259e-312  7.631259e-312
1  1.269749e-321  9.813390e-153  1.350775e+161
2   2.128967e-52   3.925753e-33  2.818986e+179
3  5.288991e+174  3.630707e+179   8.695236e-71

In [60]:
#Descarga el archivo "medallas" y carga el DataFrame.
medallas=pd.read_csv("files/medallas.csv",index_col="País")

In [61]:
medallas.sample(5)

               Unnamed: 0   Oro  Plata  Bronce
País
China                   1  1473    994     720
Corea del Sur           3   745    663     827
India                   6   154    202     315
Tailandia               7   132    175     278
Irán                    4   179    181     197

In [57]:
medallas.columns

Index(['País', 'Oro', 'Plata', 'Bronce'], dtype='str')

In [64]:
#Usando el loc:Usando el loc extrae todas las columnas de la fila de Tailandia.
tailandia = medallas.loc[medallas['País'] == 'Tailandia', :]

KeyError: 'País'

In [44]:
#Usando el loc extrae todas las columnas de China e Irán.

china_iran = medallas.loc[['China', 'Irán'], :]
china_iran

       Unnamed: 0   Oro  Plata  Bronce
País
China           1  1473    994     720
Irán            4   179    181     197

In [48]:
if 'Unnamed: 0' in medallas.columns: medallas.drop(columns=['Unnamed: 0'], inplace=True)
medallas.head() # Echamos un vistazo rápido

                Oro  Plata  Bronce
País
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827
Irán            179    181     197
Kazajistán      155    158     224